### Пример работы с интервалами

In [2]:
import sys
from pathlib import Path
current_path = Path.cwd()
project_path = current_path.parent
sys.path.append(str(project_path))

In [3]:
from intervals_metrics import calculate_similarity, CompositeInterval

int1 = (0, 10)  # Simple interval
int2 = [(5, 15), (0, 1)]  # Composite interval

# Calculate similarity between two intervals
print("Two intervals:")
print(f"Interval 1: {CompositeInterval(int1)}")
print(f"Interval 2: {CompositeInterval(int2)}")

print('\nSimilarities:')
sim = calculate_similarity(int1, int2, method='jaccard')
print(f"Jaccard similarity: {sim}")

sim = calculate_similarity(int1, int2, method='hausdorff')
print(f"Hausdorff similarity: {sim}")

sim = calculate_similarity(int1, int2, method='overlap')
print(f"Overlap similarity: {sim}")

sim = calculate_similarity(
    int1, int2, 
    method='mixed',
    methods=['jaccard', 'hausdorff', 'overlap'], 
    weights=[2, 5, 3]
)
print(f"Mixed similarity: {sim}")

Two intervals:
Interval 1: CompositeInterval(intervals=(0, 10))
Interval 2: CompositeInterval(intervals=[(5, 15), (0, 1)])

Similarities:
Jaccard similarity: 0.4
Hausdorff similarity: 1.0
Overlap similarity: 0.6
Mixed similarity: 0.76


### Пример построения матрицы сходств

In [4]:
from intervals_metrics import calculate_similarity_matrix

intervals = [
    (0, 10),
    (5, 10),
    [(5, 15), (0, 1)],
    [(20, 30), (25, 35)]
]

print("\nSimilarity matrix:")
sim_matrix = calculate_similarity_matrix(intervals, method='jaccard')
print(sim_matrix)

print("\nMixed similarity matrix:")
mixed_matrix = calculate_similarity_matrix(
    intervals,
    method='mixed',
    methods=['hausdorff', 'jaccard'],
    weights=[10, 90]
)
print(mixed_matrix)


Similarity matrix:
[[1.         0.5        0.4        0.        ]
 [0.5        1.         0.45454545 0.        ]
 [0.4        0.45454545 1.         0.        ]
 [0.         0.         0.         1.        ]]

Mixed similarity matrix:
[[1.         0.55       0.46       0.07142857]
 [0.55       1.         0.50909091 0.06666667]
 [0.46       0.50909091 1.         0.08571429]
 [0.07142857 0.06666667 0.08571429 1.        ]]


### Пример добавления новой метрики (имя парсится из имени класса):

In [5]:
from intervals_metrics import register_similarity_method, IntervalSimilarityMethod
from intervals_metrics import CompositeInterval
import numpy as np

@register_similarity_method
class CosineMethod(IntervalSimilarityMethod):
    def calculate(self, int1: CompositeInterval, int2: CompositeInterval, **kwargs) -> float:
        """
        Calculate cosine similarity by treating intervals as binary vectors
        over their union domain
        """
        # Это просто пример – реализуйте здесь свою метрику
        intersection = int1.intersection(int2)
        if intersection == 0:
            return 0
        return float(intersection / (np.sqrt(int1.length() * int2.length())))
    

int1 = (0, 10)
int2 = [(5, 15), (0, 1)]

sim = calculate_similarity(int1, int2, method='cosine')
print(f"Cosine similarity: {sim}")

Cosine similarity: 0.5720775535473553
